/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 logo.gltf -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Path: THREE.Mesh;
  };
  materials: {};
};

export function Logo(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/logo.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Path.geometry}
          material={nodes.Path.material}
          position={[0, 250, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/logo.gltf");
